import { useState, useEffect } from "react";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Train, Calendar, MapPin, Users, Download } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import jsPDF from 'jspdf';

interface Booking {
  id: string;
  booking_id: string;
  passenger_name: string;
  passenger_age: number;
  passenger_gender: string;
  journey_date: string;
  seat_numbers: string[];
  coach: string;
  class: string;
  total_amount: number;
  status: string;
  created_at: string;
  trains: {
    name: string;
    number: string;
    departure_time: string;
    arrival_time: string;
    stations_from: { name: string; code: string } | null;
    stations_to: { name: string; code: string } | null;
  };
}

const MyBookings = () => {
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [loading, setLoading] = useState(true);
  const { user } = useAuth();
  const { toast } = useToast();

  useEffect(() => {
    if (user) {
      fetchBookings();
    }
  }, [user]);

  const fetchBookings = async () => {
    try {
      const { data, error } = await supabase
        .from('bookings')
        .select(`
          *,
          trains (
            name,
            number,
            departure_time,
            arrival_time,
            stations_from:from_station_id (name, code),
            stations_to:to_station_id (name, code)
          )
        `)
        .eq('user_id', user?.id)
        .order('created_at', { ascending: false });

      if (error) throw error;
      setBookings(data || []);
    } catch (error) {
      console.error('Error fetching bookings:', error);
      toast({
        title: "Error",
        description: "Failed to fetch bookings",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  const downloadTicket = (booking: Booking) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(34, 85, 136);
    doc.text('RailEase - E-Ticket', 20, 20);
    
    // Booking details
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Booking ID: ${booking.booking_id}`, 20, 40);
    doc.text(`Train: ${booking.trains.name} (${booking.trains.number})`, 20, 50);
    doc.text(`From: ${booking.trains.stations_from?.name || 'Unknown'} (${booking.trains.stations_from?.code || 'N/A'})`, 20, 60);
    doc.text(`To: ${booking.trains.stations_to?.name || 'Unknown'} (${booking.trains.stations_to?.code || 'N/A'})`, 20, 70);
    doc.text(`Date: ${new Date(booking.journey_date).toLocaleDateString()}`, 20, 80);
    doc.text(`Departure: ${booking.trains.departure_time}`, 20, 90);
    doc.text(`Arrival: ${booking.trains.arrival_time}`, 20, 100);
    
    // Passenger details
    doc.text(`Passenger: ${booking.passenger_name}`, 20, 120);
    doc.text(`Age: ${booking.passenger_age}`, 20, 130);
    doc.text(`Gender: ${booking.passenger_gender}`, 20, 140);
    doc.text(`Coach: ${booking.coach}`, 20, 150);
    doc.text(`Class: ${booking.class}`, 20, 160);
    doc.text(`Seats: ${booking.seat_numbers.join(', ')}`, 20, 170);
    doc.text(`Amount: ₹${booking.total_amount}`, 20, 180);
    doc.text(`Status: ${booking.status.toUpperCase()}`, 20, 190);
    
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by RailEase - Keep this ticket for verification', 20, 270);
    
    doc.save(`RailEase-Ticket-${booking.booking_id}.pdf`);
    
    toast({
      title: "Success",
      description: "Ticket downloaded successfully"
    });
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="animate-pulse text-lg">Loading your bookings...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-foreground mb-2">My Bookings</h1>
          <p className="text-muted-foreground">View and manage your train reservations</p>
        </div>

        {bookings.length === 0 ? (
          <Card>
            <CardContent className="p-8 text-center">
              <Train className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
              <h3 className="text-lg font-medium mb-2">No bookings found</h3>
              <p className="text-muted-foreground">You haven't made any train reservations yet.</p>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-6">
            {bookings.map((booking) => (
              <Card key={booking.id} className="overflow-hidden">
                <CardHeader className="bg-primary/5">
                  <div className="flex items-center justify-between">
                    <CardTitle className="flex items-center gap-2">
                      <Train className="h-5 w-5 text-primary" />
                      {booking.trains.name} - {booking.trains.number}
                    </CardTitle>
                    <Badge variant={booking.status === 'confirmed' ? 'default' : 'secondary'}>
                      {booking.status.toUpperCase()}
                    </Badge>
                  </div>
                  <p className="text-sm text-muted-foreground">Booking ID: {booking.booking_id}</p>
                </CardHeader>
                <CardContent className="p-6">
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                    {/* Route Information */}
                    <div className="space-y-2">
                      <div className="flex items-center gap-2 text-sm font-medium">
                        <MapPin className="h-4 w-4 text-primary" />
                        Route
                      </div>
                      <div className="text-sm">
                        <div>{booking.trains.stations_from?.name || 'Unknown'}</div>
                        <div className="text-muted-foreground">↓</div>
                        <div>{booking.trains.stations_to?.name || 'Unknown'}</div>
                      </div>
                    </div>

                    {/* Journey Details */}
                    <div className="space-y-2">
                      <div className="flex items-center gap-2 text-sm font-medium">
                        <Calendar className="h-4 w-4 text-primary" />
                        Journey
                      </div>
                      <div className="text-sm">
                        <div>{new Date(booking.journey_date).toLocaleDateString()}</div>
                        <div className="text-muted-foreground">
                          {booking.trains.departure_time} - {booking.trains.arrival_time}
                        </div>
                      </div>
                    </div>

                    {/* Passenger Details */}
                    <div className="space-y-2">
                      <div className="flex items-center gap-2 text-sm font-medium">
                        <Users className="h-4 w-4 text-primary" />
                        Passenger
                      </div>
                      <div className="text-sm">
                        <div>{booking.passenger_name}</div>
                        <div className="text-muted-foreground">
                          {booking.passenger_age}yr, {booking.passenger_gender}
                        </div>
                      </div>
                    </div>

                    {/* Seat Details */}
                    <div className="space-y-2">
                      <div className="text-sm font-medium">Seat Details</div>
                      <div className="text-sm">
                        <div>Coach {booking.coach} - {booking.class}</div>
                        <div className="text-muted-foreground">
                          Seats: {booking.seat_numbers.join(', ')}
                        </div>
                        <div className="font-medium text-primary">₹{booking.total_amount}</div>
                      </div>
                    </div>
                  </div>

                  <div className="mt-6 flex justify-end">
                    <Button 
                      onClick={() => downloadTicket(booking)}
                      variant="outline" 
                      className="flex items-center gap-2"
                    >
                      <Download className="h-4 w-4" />
                      Download Ticket
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default MyBookings;