// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bympgnknrvaqttiofjyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5bXBnbmtucnZhcXR0aW9manl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTQyNDEsImV4cCI6MjA3MjA3MDI0MX0.yPj1lDHIYJFDhJdgZAcWlZ78Pz_M9nPr8sGxxbdTtnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});